
training_run:
  model: "models.no_input_model.AudioFilterEstimatorFreq"
  loss_function: "training.loss_functions.acc_loss"
  loss_weights:
    - 0.66
    - 0.34
  inner_loop_iterations: 1
  epochs: 10
  learning_rate: 0.005
  batch_size: 128
  n_gpus: 2
  filter_length: 4096
  sound_snip_length: 50 #ms
  limit_used_sound_snips: 10000
  sound_dataset_path: "/home/ai/datasets/audio/LibriSpeech/train-clean-100/"
  rir_dataset_path: "/home/ai/datasets/audio/dataset/shoebox/run2/train/"
  savepath: "exp/test_no_input_acc_loss/t3-5e-3"
  checkpointing_mode: "all" #all/last/none
  log_to_wandb: true
  wandb_key_path: "/home/ai/.wandb.key"

validation_run: #use the model settings from training_run but explicitly uses a new path for validation
  sound_dataset_path: "/home/ai/datasets/audio/LibriSpeech/train-clean-100/"
  rir_dataset_path: "/home/ai/datasets/audio/dataset/shoebox/run2/val/"
  metrics: #these need to be implemented
    - "ac"

testing_run: #use the model settings from training run but explicitly uses a new path for the testing data
  enable: false
  sound_dataset_path: "/home/ai/datasets/audio/LibriSpeech/train-clean-100/2002/"
  rir_dataset_path: "/home/ai/datasets/audio/dataset/shoebox/run2/test/"
  metrics:
    - "ac"
  baseline_filters:
    - "vast"
    - "acc"
    - "pm"
    - "dirac"


