
training_run:
  model: "models.modified_sann.AudioFilterEstimatorFreq"
  loss_function: "training.loss_functions.acc_loss"
  inner_loop_iterations: 0
  epochs: 1
  learning_rate: 0.000
  batch_size: 1
  n_gpus: 0
  filter_length: 4096
  sound_snip_length: 5000 #ms
  limit_used_sound_snips: 100
  sound_dataset_path: "/home/ai/datasets/audio/LibriSpeech/train-clean-100/2002/"
  rir_dataset_path: "/home/ai/datasets/audio/dataset/shoebox/run2/train/"
  savepath: "exp/test_train_with_acc_loss"
  checkpointing_mode: "all" #all/last/none
  log_to_wandb: false
  wandb_key_path: "/home/ai/.wandb.key"

validation_run: #use the model settings from training_run but explicitly uses a new path for validation
  sound_dataset_path: "/home/ai/datasets/audio/LibriSpeech/train-clean-100/2007/"
  rir_dataset_path: "/home/ai/datasets/audio/dataset/shoebox/run2/val/"
  metrics: #these need to be implemented
    - "acc"


testing_run: #use the model settings from training run but explicitly uses a new path for the testing data
  enable: false
  sound_dataset_path: "../testing_data/audio_raw/"
  rir_dataset_path: "../testing_data/rirs/test_rirs/dataset/shoebox/alfredo-request/test/"
  metrics:
    - "acc"


